
# manifest for Network Watcher
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-network-watcher
  namespace: operator
---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-watcher
  namespace: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: network-watcher
  template:
    metadata:
      labels:
        name: network-watcher
    spec:
      serviceAccountName: service-account-network-watcher
      containers:
      - name: network-watcher
        image: smodou/network-watcher:latest
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: SERVICE_CREATE_EVENT_URL
          value: "http://service-network-watcher-mock.operator.svc.cluster.local/service/post"
        - name: SERVICE_UPDATE_EVENT_URL
          value: "http://service-network-watcher-mock.operator.svc.cluster.local/service/put"
        - name: SERVICE_DELETE_EVENT_URL
          value: "http://service-network-watcher-mock.operator.svc.cluster.local/service/delete"
        - name: IN_CLUSTER 
          value: "true" 
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "network-watcher"
        - name: "USERNAME"
          valueFrom:
            secretKeyRef:
              name: secret-mock
              key: username
        - name: "PASSWORD"
          valueFrom:
            secretKeyRef:
              name: secret-mock
              key: password
        - name: "URL_SERVICE"
          valueFrom:
            secretKeyRef:
              name: secret-mock
              key: url-service

      
      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: network-watcher
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - cnocd.beopenit.com
  resources:
  - workloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cnocd.beopenit.com
  resources:
  - workloads/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - update


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: network-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: network-watcher
subjects:
- kind: ServiceAccount
  name: service-account-network-watcher
  namespace: operator

---

# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: network-watcher-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: network-watcher-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: network-watcher-leader-election-role
subjects:
- kind: ServiceAccount
  name: service-account-network-watcher
  namespace: operator

---

# Credentials to authicate to the api-mock
apiVersion: v1
kind: Secret
metadata:
  name: secret-mock
  namespace: operator
type: Opaque
data:
  username: bW9kb3U=
  password: dGVzdA==
  url-service: MTAuMjQ0LjAuMTg2OjMxMDE1L3NlcnZpY2UvcG9zdAo=
---


